# Version 2 without namespacing. Required env variables :
# ART_PRIMARY_LICENSE
# ART_LICENSES
# ART_LOGIN (optional, default=admin)
# ART_PASSWORD (optional, default=password)
#
version: '2'
services:
  artifactory_1:
    image: alexistjfrog-docker-registry.bintray.io/artifactoryhaprimary:4.7.7
    volumes:
      - "/etc/opt/jfrog/artifactory"
      - "/var/opt/jfrog/artifactory/data"
      - clusterhome:/var/opt/jfrog/cluster
    environment:
      - DATABASE_CONNECTION_STRING=jdbc:mysql://mysqldb:3306/artdb?characterEncoding=UTF-8&elideSetAutoCommits=true
      - DATABASE_USER=artifactory
      - DATABASE_PASSWORD=password
      - ART_PRIMARY_LICENSE
      - ART_LICENSES
    depends_on:
      - mysqldb

  artifactory_2:
    image: alexistjfrog-docker-registry.bintray.io/artifactoryhasecondary:4.7.7
    volumes:
      - "/etc/opt/jfrog/artifactory"
      - "/var/opt/jfrog/artifactory/data"
      - clusterhome:/var/opt/jfrog/cluster
    environment:
      - PRIMARY_BASE_URL=http://artifactory_1:8081/artifactory
      - ART_LOGIN=admin
      - ART_PASSWORD=password
    depends_on:
      - artifactory_1
      - mysqldb

  nginx:
    image: alexistjfrog-docker-registry.bintray.io/artifactoryhanginx:1.10.0
    ports:
      - "80:80"
      - "443:443"
      - "5000-5010:5000-5010"
    environment:
      - ART_LOGIN=admin
      - ART_PASSWORD=password
      #- ART_PRIMARY_NODE_HOST_PORT=artifactory_1:8081
      #- ART_REVERSE_PROXY_METHOD=SUBDOMAIN
      #- ART_SERVER_NAME=mycluster.local

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=artdb
      - MYSQL_USER=artifactory
      - MYSQL_PASSWORD=password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306"

volumes:
  mysqldata:
    driver: local
  clusterhome:
    driver: local

